/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protocol/client.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "client.pb-c.h"
void   ai_client__available_preset_prompts_request__init
                     (AiClient__AvailablePresetPromptsRequest         *message)
{
  static const AiClient__AvailablePresetPromptsRequest init_value = AI_CLIENT__AVAILABLE_PRESET_PROMPTS_REQUEST__INIT;
  *message = init_value;
}
size_t ai_client__available_preset_prompts_request__get_packed_size
                     (const AiClient__AvailablePresetPromptsRequest *message)
{
  assert(message->base.descriptor == &ai_client__available_preset_prompts_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ai_client__available_preset_prompts_request__pack
                     (const AiClient__AvailablePresetPromptsRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ai_client__available_preset_prompts_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ai_client__available_preset_prompts_request__pack_to_buffer
                     (const AiClient__AvailablePresetPromptsRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ai_client__available_preset_prompts_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AiClient__AvailablePresetPromptsRequest *
       ai_client__available_preset_prompts_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AiClient__AvailablePresetPromptsRequest *)
     protobuf_c_message_unpack (&ai_client__available_preset_prompts_request__descriptor,
                                allocator, len, data);
}
void   ai_client__available_preset_prompts_request__free_unpacked
                     (AiClient__AvailablePresetPromptsRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ai_client__available_preset_prompts_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ai_client__ask_for_completion__init
                     (AiClient__AskForCompletion         *message)
{
  static const AiClient__AskForCompletion init_value = AI_CLIENT__ASK_FOR_COMPLETION__INIT;
  *message = init_value;
}
size_t ai_client__ask_for_completion__get_packed_size
                     (const AiClient__AskForCompletion *message)
{
  assert(message->base.descriptor == &ai_client__ask_for_completion__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ai_client__ask_for_completion__pack
                     (const AiClient__AskForCompletion *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ai_client__ask_for_completion__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ai_client__ask_for_completion__pack_to_buffer
                     (const AiClient__AskForCompletion *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ai_client__ask_for_completion__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AiClient__AskForCompletion *
       ai_client__ask_for_completion__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AiClient__AskForCompletion *)
     protobuf_c_message_unpack (&ai_client__ask_for_completion__descriptor,
                                allocator, len, data);
}
void   ai_client__ask_for_completion__free_unpacked
                     (AiClient__AskForCompletion *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ai_client__ask_for_completion__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ai_client__terminate_completion__init
                     (AiClient__TerminateCompletion         *message)
{
  static const AiClient__TerminateCompletion init_value = AI_CLIENT__TERMINATE_COMPLETION__INIT;
  *message = init_value;
}
size_t ai_client__terminate_completion__get_packed_size
                     (const AiClient__TerminateCompletion *message)
{
  assert(message->base.descriptor == &ai_client__terminate_completion__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ai_client__terminate_completion__pack
                     (const AiClient__TerminateCompletion *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ai_client__terminate_completion__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ai_client__terminate_completion__pack_to_buffer
                     (const AiClient__TerminateCompletion *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ai_client__terminate_completion__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AiClient__TerminateCompletion *
       ai_client__terminate_completion__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AiClient__TerminateCompletion *)
     protobuf_c_message_unpack (&ai_client__terminate_completion__descriptor,
                                allocator, len, data);
}
void   ai_client__terminate_completion__free_unpacked
                     (AiClient__TerminateCompletion *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ai_client__terminate_completion__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ai_client__available_preset_prompts_request__field_descriptors[1] =
{
  {
    "askId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AiClient__AvailablePresetPromptsRequest, askid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ai_client__available_preset_prompts_request__field_indices_by_name[] = {
  0,   /* field[0] = askId */
};
static const ProtobufCIntRange ai_client__available_preset_prompts_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ai_client__available_preset_prompts_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AiClient.AvailablePresetPromptsRequest",
  "AvailablePresetPromptsRequest",
  "AiClient__AvailablePresetPromptsRequest",
  "AiClient",
  sizeof(AiClient__AvailablePresetPromptsRequest),
  1,
  ai_client__available_preset_prompts_request__field_descriptors,
  ai_client__available_preset_prompts_request__field_indices_by_name,
  1,  ai_client__available_preset_prompts_request__number_ranges,
  (ProtobufCMessageInit) ai_client__available_preset_prompts_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ai_client__ask_for_completion__field_descriptors[8] =
{
  {
    "askId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AiClient__AskForCompletion, askid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prompt",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AiClient__AskForCompletion, prompt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "basePrompt",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AiClient__AskForCompletion, baseprompt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "suffix",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AiClient__AskForCompletion, suffix),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stopTokens",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(AiClient__AskForCompletion, n_stoptokens),
    offsetof(AiClient__AskForCompletion, stoptokens),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temperature",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(AiClient__AskForCompletion, has_temperature),
    offsetof(AiClient__AskForCompletion, temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stream",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(AiClient__AskForCompletion, has_stream),
    offsetof(AiClient__AskForCompletion, stream),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxTokens",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(AiClient__AskForCompletion, has_maxtokens),
    offsetof(AiClient__AskForCompletion, maxtokens),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ai_client__ask_for_completion__field_indices_by_name[] = {
  0,   /* field[0] = askId */
  2,   /* field[2] = basePrompt */
  7,   /* field[7] = maxTokens */
  1,   /* field[1] = prompt */
  4,   /* field[4] = stopTokens */
  6,   /* field[6] = stream */
  3,   /* field[3] = suffix */
  5,   /* field[5] = temperature */
};
static const ProtobufCIntRange ai_client__ask_for_completion__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 6, 4 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor ai_client__ask_for_completion__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AiClient.AskForCompletion",
  "AskForCompletion",
  "AiClient__AskForCompletion",
  "AiClient",
  sizeof(AiClient__AskForCompletion),
  8,
  ai_client__ask_for_completion__field_descriptors,
  ai_client__ask_for_completion__field_indices_by_name,
  2,  ai_client__ask_for_completion__number_ranges,
  (ProtobufCMessageInit) ai_client__ask_for_completion__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ai_client__terminate_completion__field_descriptors[1] =
{
  {
    "completionId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AiClient__TerminateCompletion, completionid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ai_client__terminate_completion__field_indices_by_name[] = {
  0,   /* field[0] = completionId */
};
static const ProtobufCIntRange ai_client__terminate_completion__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ai_client__terminate_completion__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AiClient.TerminateCompletion",
  "TerminateCompletion",
  "AiClient__TerminateCompletion",
  "AiClient",
  sizeof(AiClient__TerminateCompletion),
  1,
  ai_client__terminate_completion__field_descriptors,
  ai_client__terminate_completion__field_indices_by_name,
  1,  ai_client__terminate_completion__number_ranges,
  (ProtobufCMessageInit) ai_client__terminate_completion__init,
  NULL,NULL,NULL    /* reserved[123] */
};
