/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protocol/server.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "server.pb-c.h"
void   ai_server__completion_status__init
                     (AiServer__CompletionStatus         *message)
{
  static const AiServer__CompletionStatus init_value = AI_SERVER__COMPLETION_STATUS__INIT;
  *message = init_value;
}
size_t ai_server__completion_status__get_packed_size
                     (const AiServer__CompletionStatus *message)
{
  assert(message->base.descriptor == &ai_server__completion_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ai_server__completion_status__pack
                     (const AiServer__CompletionStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ai_server__completion_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ai_server__completion_status__pack_to_buffer
                     (const AiServer__CompletionStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ai_server__completion_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AiServer__CompletionStatus *
       ai_server__completion_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AiServer__CompletionStatus *)
     protobuf_c_message_unpack (&ai_server__completion_status__descriptor,
                                allocator, len, data);
}
void   ai_server__completion_status__free_unpacked
                     (AiServer__CompletionStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ai_server__completion_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ai_server__completion_chunk__init
                     (AiServer__CompletionChunk         *message)
{
  static const AiServer__CompletionChunk init_value = AI_SERVER__COMPLETION_CHUNK__INIT;
  *message = init_value;
}
size_t ai_server__completion_chunk__get_packed_size
                     (const AiServer__CompletionChunk *message)
{
  assert(message->base.descriptor == &ai_server__completion_chunk__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ai_server__completion_chunk__pack
                     (const AiServer__CompletionChunk *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ai_server__completion_chunk__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ai_server__completion_chunk__pack_to_buffer
                     (const AiServer__CompletionChunk *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ai_server__completion_chunk__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AiServer__CompletionChunk *
       ai_server__completion_chunk__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AiServer__CompletionChunk *)
     protobuf_c_message_unpack (&ai_server__completion_chunk__descriptor,
                                allocator, len, data);
}
void   ai_server__completion_chunk__free_unpacked
                     (AiServer__CompletionChunk *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ai_server__completion_chunk__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ai_server__whole_completion__init
                     (AiServer__WholeCompletion         *message)
{
  static const AiServer__WholeCompletion init_value = AI_SERVER__WHOLE_COMPLETION__INIT;
  *message = init_value;
}
size_t ai_server__whole_completion__get_packed_size
                     (const AiServer__WholeCompletion *message)
{
  assert(message->base.descriptor == &ai_server__whole_completion__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ai_server__whole_completion__pack
                     (const AiServer__WholeCompletion *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ai_server__whole_completion__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ai_server__whole_completion__pack_to_buffer
                     (const AiServer__WholeCompletion *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ai_server__whole_completion__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AiServer__WholeCompletion *
       ai_server__whole_completion__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AiServer__WholeCompletion *)
     protobuf_c_message_unpack (&ai_server__whole_completion__descriptor,
                                allocator, len, data);
}
void   ai_server__whole_completion__free_unpacked
                     (AiServer__WholeCompletion *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ai_server__whole_completion__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ai_server__available_preset_prompts_response__init
                     (AiServer__AvailablePresetPromptsResponse         *message)
{
  static const AiServer__AvailablePresetPromptsResponse init_value = AI_SERVER__AVAILABLE_PRESET_PROMPTS_RESPONSE__INIT;
  *message = init_value;
}
size_t ai_server__available_preset_prompts_response__get_packed_size
                     (const AiServer__AvailablePresetPromptsResponse *message)
{
  assert(message->base.descriptor == &ai_server__available_preset_prompts_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ai_server__available_preset_prompts_response__pack
                     (const AiServer__AvailablePresetPromptsResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ai_server__available_preset_prompts_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ai_server__available_preset_prompts_response__pack_to_buffer
                     (const AiServer__AvailablePresetPromptsResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ai_server__available_preset_prompts_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AiServer__AvailablePresetPromptsResponse *
       ai_server__available_preset_prompts_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AiServer__AvailablePresetPromptsResponse *)
     protobuf_c_message_unpack (&ai_server__available_preset_prompts_response__descriptor,
                                allocator, len, data);
}
void   ai_server__available_preset_prompts_response__free_unpacked
                     (AiServer__AvailablePresetPromptsResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ai_server__available_preset_prompts_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ai_server__error__init
                     (AiServer__Error         *message)
{
  static const AiServer__Error init_value = AI_SERVER__ERROR__INIT;
  *message = init_value;
}
size_t ai_server__error__get_packed_size
                     (const AiServer__Error *message)
{
  assert(message->base.descriptor == &ai_server__error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ai_server__error__pack
                     (const AiServer__Error *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ai_server__error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ai_server__error__pack_to_buffer
                     (const AiServer__Error *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ai_server__error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AiServer__Error *
       ai_server__error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AiServer__Error *)
     protobuf_c_message_unpack (&ai_server__error__descriptor,
                                allocator, len, data);
}
void   ai_server__error__free_unpacked
                     (AiServer__Error *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ai_server__error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const protobuf_c_boolean ai_server__completion_status__stream__default_value = 0;
static const ProtobufCFieldDescriptor ai_server__completion_status__field_descriptors[4] =
{
  {
    "askId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AiServer__CompletionStatus, askid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "completionId",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AiServer__CompletionStatus, completionid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AiServer__CompletionStatus, status),
    &ai_server__status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stream",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(AiServer__CompletionStatus, stream),
    NULL,
    &ai_server__completion_status__stream__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ai_server__completion_status__field_indices_by_name[] = {
  0,   /* field[0] = askId */
  1,   /* field[1] = completionId */
  2,   /* field[2] = status */
  3,   /* field[3] = stream */
};
static const ProtobufCIntRange ai_server__completion_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ai_server__completion_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AiServer.CompletionStatus",
  "CompletionStatus",
  "AiServer__CompletionStatus",
  "AiServer",
  sizeof(AiServer__CompletionStatus),
  4,
  ai_server__completion_status__field_descriptors,
  ai_server__completion_status__field_indices_by_name,
  1,  ai_server__completion_status__number_ranges,
  (ProtobufCMessageInit) ai_server__completion_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ai_server__completion_chunk__field_descriptors[2] =
{
  {
    "completionId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AiServer__CompletionChunk, completionid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AiServer__CompletionChunk, content),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ai_server__completion_chunk__field_indices_by_name[] = {
  0,   /* field[0] = completionId */
  1,   /* field[1] = content */
};
static const ProtobufCIntRange ai_server__completion_chunk__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ai_server__completion_chunk__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AiServer.CompletionChunk",
  "CompletionChunk",
  "AiServer__CompletionChunk",
  "AiServer",
  sizeof(AiServer__CompletionChunk),
  2,
  ai_server__completion_chunk__field_descriptors,
  ai_server__completion_chunk__field_indices_by_name,
  1,  ai_server__completion_chunk__number_ranges,
  (ProtobufCMessageInit) ai_server__completion_chunk__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ai_server__whole_completion__field_descriptors[4] =
{
  {
    "completionId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AiServer__WholeCompletion, completionid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AiServer__WholeCompletion, content),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(AiServer__WholeCompletion, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "askId",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AiServer__WholeCompletion, askid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ai_server__whole_completion__field_indices_by_name[] = {
  3,   /* field[3] = askId */
  0,   /* field[0] = completionId */
  1,   /* field[1] = content */
  2,   /* field[2] = timestamp */
};
static const ProtobufCIntRange ai_server__whole_completion__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ai_server__whole_completion__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AiServer.WholeCompletion",
  "WholeCompletion",
  "AiServer__WholeCompletion",
  "AiServer",
  sizeof(AiServer__WholeCompletion),
  4,
  ai_server__whole_completion__field_descriptors,
  ai_server__whole_completion__field_indices_by_name,
  1,  ai_server__whole_completion__number_ranges,
  (ProtobufCMessageInit) ai_server__whole_completion__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ai_server__available_preset_prompts_response__field_descriptors[2] =
{
  {
    "askId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AiServer__AvailablePresetPromptsResponse, askid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "names",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(AiServer__AvailablePresetPromptsResponse, n_names),
    offsetof(AiServer__AvailablePresetPromptsResponse, names),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ai_server__available_preset_prompts_response__field_indices_by_name[] = {
  0,   /* field[0] = askId */
  1,   /* field[1] = names */
};
static const ProtobufCIntRange ai_server__available_preset_prompts_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ai_server__available_preset_prompts_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AiServer.AvailablePresetPromptsResponse",
  "AvailablePresetPromptsResponse",
  "AiServer__AvailablePresetPromptsResponse",
  "AiServer",
  sizeof(AiServer__AvailablePresetPromptsResponse),
  2,
  ai_server__available_preset_prompts_response__field_descriptors,
  ai_server__available_preset_prompts_response__field_indices_by_name,
  1,  ai_server__available_preset_prompts_response__number_ranges,
  (ProtobufCMessageInit) ai_server__available_preset_prompts_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ai_server__error__field_descriptors[3] =
{
  {
    "requestId",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AiServer__Error, requestid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(AiServer__Error, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "messageString",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AiServer__Error, messagestring),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ai_server__error__field_indices_by_name[] = {
  1,   /* field[1] = code */
  2,   /* field[2] = messageString */
  0,   /* field[0] = requestId */
};
static const ProtobufCIntRange ai_server__error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ai_server__error__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AiServer.Error",
  "Error",
  "AiServer__Error",
  "AiServer",
  sizeof(AiServer__Error),
  3,
  ai_server__error__field_descriptors,
  ai_server__error__field_indices_by_name,
  1,  ai_server__error__number_ranges,
  (ProtobufCMessageInit) ai_server__error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ai_server__status__enum_values_by_number[2] =
{
  { "STARTED", "AI_SERVER__STATUS__STARTED", 0 },
  { "ENDED", "AI_SERVER__STATUS__ENDED", 1 },
};
static const ProtobufCIntRange ai_server__status__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex ai_server__status__enum_values_by_name[2] =
{
  { "ENDED", 1 },
  { "STARTED", 0 },
};
const ProtobufCEnumDescriptor ai_server__status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "AiServer.Status",
  "Status",
  "AiServer__Status",
  "AiServer",
  2,
  ai_server__status__enum_values_by_number,
  2,
  ai_server__status__enum_values_by_name,
  1,
  ai_server__status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
